rm -rf *gofr*
rm -rf *gave*
rm -rf ../../Risultati/Gas/ave_epot*
rm -rf ../../Risultati/Gas/ave_pres*
rm -rf ../../Risultati/Gas/ave_etot*
rm -rf ../../Risultati/Gas/ave_ekin*
rm -rf frames/*.xyz
rm -rf seed.out
rm -rf config.final
rm -rf ../../Risultati/Gas/output_restart.dat
rm -rf ../../Risultati/Gas/ave_temp*
